services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /srv/data/storage:/srv
      - /srv/data/filebrowser/database:/database
      - /srv/data/filebrowser/config:/config
    ports:
      - "8003:80"
    user: "0:0"
    restart: unless-stopped
