services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/data/portainer/data:/data
    # ports:
    # - 9443:9443 # https
    # - 9000:9000 # http
    networks:
      - proxy

networks:
  proxy:
    external: true
