services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts@sha256:1ae8e65d50ca5498cb2c33e617495a1e3ef245b0d2392b4a44c70ae09b822891
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/data/portainer/data:/data
    ports:
      - "9000:9000"
