services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest@sha256:1b806d19dc993513e0e79bbe8ba586bef9ee9b8ab23182efd88e0f4e6337bf17
    container_name: grampsweb
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - grampsweb-internal
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb_redis
    volumes:
      - /srv/data/grampsweb/users:/app/users
      - /srv/data/grampsweb/indexdir:/app/indexdir
      - /srv/data/grampsweb/thumbnail_cache:/app/thumbnail_cache
      - /srv/data/grampsweb/cache:/app/cache
      - /srv/data/grampsweb/secret:/app/secret
      - /srv/data/grampsweb/grampsdb:/root/.gramps/grampsdb
      - /srv/data/grampsweb/media:/app/media
      - /srv/data/grampsweb/tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO --concurrency=2

  grampsweb_redis:
    image: docker.io/library/redis:7.2.4-alpine@sha256:c8bb255c3559b3e458766db810aa7b3c7af1235b204cfdb304e79ff388fe1a5a
    container_name: grampsweb_redis
    networks:
      - grampsweb-internal
    restart: unless-stopped

networks:
  grampsweb-internal:
    driver: bridge
