services:
  koillection:
    image: koillection/koillection:v1.11.1@sha256:22657fe06bccac4507da01b0e745d78dd4054a1443217a5f284a9c52005e660d
    container_name: koillection
    restart: unless-stopped
    ports:
      - "8002:80"
    networks:
      - koillection-internal
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - /srv/data/koillection/uploads:/uploads

  db:
    image: postgres:16@sha256:2586e2a95d1c9b31cb2967feb562948f7d364854453d703039b6efa45fe48417
    container_name: koillection-db
    restart: unless-stopped
    networks:
      - koillection-internal
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - /var/lib/docker-data/koillection/db:/var/lib/postgresql/data

networks:
  koillection-internal:
    driver: bridge
