---
all:
  children:
    homelab:
      hosts:
        docker-host:
          ansible_host: 10.10.10.10 # match terraform lxc_ip
          ansible_user: root
          # ansible_ssh_common_args: '-o ProxyJump=root@192.168.68.14'
