---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    storage:
      hosts:
        storage-host:
          ansible_host: 10.10.10.10
          ansible_user: root
    dns:
      hosts:
        dns-host:
          ansible_host: 10.10.10.20
          ansible_user: root
    caddy:
      hosts:
        caddy-host:
          ansible_host: 10.10.10.30
          ansible_user: root
    tunnel:
      hosts:
        tunnel-host:
          ansible_host: 10.10.10.40
          ansible_user: root
    homelab:
      hosts:
        docker-host:
          ansible_host: 10.10.10.50
          ansible_user: root
