---
all:
  children:
    homelab:
      hosts:
        docker-host:
          ansible_host: 10.10.10.10 # match terraform lxc_ip
          ansible_user: root
    tunnel:
      hosts:
        tunnel-host:
          ansible_host: 10.10.10.20 # match terraform tunnel_lxc_ip
          ansible_user: root
