services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped

    network_mode: host

    volumes:
      - /srv/data/samba-fileshare:/shares/files

    environment:
      - TZ=${TZ}

    command: >
      -u "${SMB_USER};${SMB_PASS}"
      -s "files;/shares/files;yes;no;yes"
