pageInfo:
  title: dashy
appConfig:
  auth:
    users:
      - user: username_change_me
        hash: hash_password_change_me
        type: admin
  layout: auto
  iconSize: small
  theme: callisto
sections:
  - name: Monitoring
    icon: fas fa-server
    items:
      - title: Dozzle
        icon: fas fa-server
        url: http://server_change_me:8080
  - name: Applications
    icon: fas fa-th
    items:
      - title: Koillection
        icon: fas fa-box-open
        url: http://server_change_me:8090
