services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    volumes:
      - ./conf.yml:/app/user-data/conf.yml
    # ports:
    #   - 8080:8080
    networks:
      - proxy
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  proxy:
    external: true