---
- name: Provision homelab Docker host
  hosts: homelab
  become: true

  roles:
    - common
    - docker
    - directories
    - docker_network
    - caddy
    - stacks
    - borgbackup

- name: Provision Cloudflare tunnel
  hosts: tunnel
  become: true

  roles:
    - common
    - cloudflared
