services:
  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "3011:3000"
    networks:
      - adventurelog-internal
    depends_on:
      - server

  db:
    image: postgis/postgis:16-3.5
    container_name: adventurelog-db
    restart: unless-stopped
    env_file: .env
    networks:
      - adventurelog-internal
    volumes:
      - /srv/data/adventurelog/data:/var/lib/postgresql/data/

  server:
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8001:80"
    networks:
      - adventurelog-internal
    depends_on:
      - db
    volumes:
      - /srv/data/adventurelog/media:/code/media/

networks:
  adventurelog-internal:
    driver: bridge
