services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - /srv/data/ollama/models:/root/.ollama
    networks:
      - ai

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    depends_on:
      - ollama
    # ports:
    #   - "3001:8080"
    volumes:
      - /srv/data/openwebui/data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - ai
      - proxy

networks:
  ai:
    driver: bridge
  proxy:
    external: true